<!-- Modal -->
<div id='customerEditModal'class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="customerModallbl" aria-hidden="true">
    <form id='frm_admin_edit_customer' class='form-horizontal'>
        <input type='hidden' id='customerEditIDLastLoaded' name='customerEditIDLastLoaded' value='' />
        <div id='customerEditModalDynamic'></div>
        <div class='modal-footer'>
            <button id='customerModalCloseBtn' cclass='btn' data-dismiss='modal' aria-hidden='true'>
                <i class='icon-remove-sign'></i>&nbsp;Close
            </button>
            <button id='customerModalSaveBtn' class="btn btn-success" type='button'>
                <i class='icon-ok-sign icon-white'></i>&nbsp;Save changes
            </button>
        </div>
    </form>
</div>