<!-- /***** IMPORT CUSTOMERS FORM *****/ -->
<form id="frm_admin_import_customers" class="form-horizontal" method="POST" enctype="multipart/form-data">
    <div id="importCustomersModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="importCustomersModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times</button>
            <h3 id="importCustomersModalLabel">Import Customers</h3>
        </div>
        <div class="modal-body">

            <div id='customerImportResultsDynamic'></div>

            <div class='clearfix'></div>

            <!-- Cart Owner -->
            <div class="control-group">
                <label class="control-label" for="cartID">Cart Owner</label>
                <div class="controls">
                    <select id="cartID" name="cartID">
                        <?php
                        $cart = new killerCart\Cart($_SESSION['cartID']);
                        foreach ($cart->getCartIDs('All') as $k => $v) {
                            // ACL Check
                            if ($_SESSION['groupID'] != 1 && ($v['cartID'] != $_SESSION['cartID'])
                            ) {
                                continue;
                            }
                            $s = $cart->getCartInfo($v['cartID']);
                            ?>
                            <option value='<?php echo $s['cartID']; ?>'><?php echo $s['cartName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <!-- Group -->
            <div class="control-group">
                <label class="control-label" for="groupID">
                    Group
                </label>
                <div class="controls">
                    <select id='groupID' name='groupID' class='span2'>
                        <option value='0' selected>General (Public)</option>
                        <option value='1'>Member (Private)</option>
                    </select>
                </div>
            </div>

            <!-- CSV File -->
            <div class="control-group">
                <label class="control-label" for="groupID">
                    CSV File
                </label>
                <div class="controls">
                    <input type='file' name='csvFile' id='csvFile' />
                </div>
            </div>

            <!-- Notice -->
            <div class='alert alert-info'>
                <h4><i class='icon-info-sign'></i>&nbsp;Note:</h4>
                <p>The CSV file <strong>MUST</strong> be in the following format or it will be rejected:</p>
                <p>The columns marked with an asterisk(*) are required, the rest are optional and can be left blank to skip.</p>
                <p><strong>Note:</strong> column names are not case sensitive, however, they must match otherwise (e.g. CompanyName does not have a space in it)</p>
                <ul>
                    <li><strong>Required Columns*:</strong> Username, Passphrase, Email</li>
                    <li>If a value includes a comma, surround the value with double-quotes (e.g. "Company, Inc.")</li>
                    <li><strong>1st Row (Column Names):</strong> Username,Email,Passphrase,CompanyName</li>
                    <li><strong>Nth Row (Data):</strong> Username,Em@il.com,P@$$phr4se,"Company Name, Inc."</li>
                </ul>
            </div>

        </div>

        <div class="modal-footer">
            <button id="importCustomersCloseBtn" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>

    </div><!--#div_admin_new_customer-->

</form><!--#frm_admin_new_customer-->


<?php
$pageJavaScript[] = "
    <script type='text/javascript'>
        $(document).ready(function() {
            
            document.getElementById('csvFile').addEventListener('change', function(e) {
            
                // Upload File
                var file = this.files[0];
                var xhr = new XMLHttpRequest();
                xhr.file = file; // not necessary if you create scopes like this
                xhr.addEventListener('progress', function(e) {
                    var done = e.position || e.loaded, total = e.totalSize || e.total;
                    console.log('xhr progress: ' + (Math.floor(done/total*1000)/10) + '%');
                }, false);
                if ( xhr.upload ) {
                    xhr.upload.onprogress = function(e) {
                        var done = e.position || e.loaded, total = e.totalSize || e.total;
                        console.log('xhr.upload progress: ' + done + ' / ' + total + ' = ' + (Math.floor(done/total*1000)/10) + '%');
                    };
                }
                xhr.onreadystatechange = function(e) {
                    if ( 4 == this.readyState ) {
                        console.log(['xhr upload complete', e]);
                    }
                };
                
                // Send Form Post
                var url = '" . cartPublicUrl . "admin/?p=customer';
                xhr.open('post', url, true);
                
                // Form Data
                var fd = new FormData;
                fd.append('csvFile', file);
                fd.append('m', 'ajax');
                fd.append('p', 'customer');
                fd.append('a', 'importCustomers');
                fd.append('cartID', $('#cartID').val());
                fd.append('groupID', $('#groupID').val());
                
                // Results
                console.log('Results:');
                xhr.onload = function() {
                    $('#customerImportResultsDynamic').html(this.responseText);
                };
                xhr.send(fd);
                
            }, false);

            // Admin :: Customer :: Import Modal :: Close :: Refresh Page (if needed)
            $('#importCustomersCloseBtn').click(function() {
                var refresh = $('#customerImportResultsDynamic').html();
                if (refresh != '') {
                    location.reload();
                }
            });
            
        });
    </script>
";