<?php
//
// AJAX
//
if (!empty($_POST['m']) && $_POST['m'] == 'ajax'
) {

    \Errors::debugLogger('['.__FILE__.':'.__LINE__.'] Ajax Post...', 1, true);
    
    //
    // Load Customer Page
    //
    if (!empty($_POST['a']) && $_POST['a'] == 'loadPage'
    ) {
        
        \Errors::debugLogger('['.__FILE__.':'.__LINE__.'] Load Page...', 1, true);

        // Sanitize & Validate
        $s      = new killerCart\Sanitize();
        $pageID = $s->filterSingle($_POST['pageID'], FILTER_SANITIZE_STRING);
        
        \Errors::debugLogger('['.__FILE__.':'.__LINE__.'] Page ID: '.$pageID.'...', 1, true);
        
        // Load Content
        switch ($pageID) {
            case "profile": {
                    include(cartPrivateDir . 'templates/' . $_SESSION['cartTheme'] . '/customer/customer_profile.inc.phtml');
                    break;
                }
            case "addresses": {
                    include(cartPrivateDir . 'templates/' . $_SESSION['cartTheme'] . '/customer/customer_addresses.inc.phtml');
                    break;
                }
            case "paymentMethods": {
                    include(cartPrivateDir . 'templates/' . $_SESSION['cartTheme'] . '/customer/customer_payment_methods.inc.phtml');
                    break;
                }
            case "orders": {
                    include(cartPrivateDir . 'templates/' . $_SESSION['cartTheme'] . '/customer/customer_orders.inc.phtml');
                    break;
                }
            default: {
                    break;
                }
        }
    }

    // End AJAX
    exit();
}
?>
<!-- Navigation -->
<div id='customer_nav' class='container'>
    <div class='row'>
        <div class='span12'>
            <ul class="nav nav-tabs">
                <li class='active'><a href="#profile" id='defaultTab' class='customerHomeTab' data-toggle="tab"><i class='icon-user'></i>&nbsp;Profile</a></li>
                <li><a href="#addresses" class='customerHomeTab' data-toggle="tab"><i class='icon-envelope'></i>&nbsp;Addresses</a></li>
                <li><a href="#paymentMethods" class='customerHomeTab' data-toggle="tab"><i class='icon-briefcase'></i>&nbsp;Payment Methods</a></li>
                <li><a href="#orders" class='customerHomeTab' data-toggle="tab"><i class='icon-th-list'></i>&nbsp;Orders</a></li>
            </ul>
        </div>
    </div>
</div>

<!-- Content Holders -->
<div class="tab-content">
    <div class="tab-pane active" id="profile"></div>
    <div class="tab-pane" id="addresses"></div>
    <div class="tab-pane" id="paymentMethods"></div>
    <div class="tab-pane" id="orders"></div>
</div>

<?php
$pageJavaScript[] = "
    <script type='text/javascript'>
        $(document).ready(function() {
            $('.customerHomeTab').click(function() {
                var ID = $(this).attr('href').split('#')[1];
                var divID = '#'+ID;
                var div = $(divID);
                // Return if already loaded
                if (div.html() != '') {
                    return true;
                }
                // AJAX to fill content on first load
                var go = $.ajax({
                    type: 'POST',
                    url: '" . cartPublicUrl . "?p=account',
                    data: {m: 'ajax',
                        p: 'account',
                        customerID: '".$_REQUEST['customerID']."',
                        a: 'loadPage',
                        pageID: ID
                    }
                })
                .done(function(results) {
                    div.html(results);
                })
                .fail(function(msg) {
                    alert('Error: ' + msg);
                })
                .always(function() {
                });
            });
            $('#defaultTab').click();
        });
    </script>
";
?>