<?php
//
// ACL Check
//
if ($_SESSION['user']['usergroup']['usergroupID'] == 1) {
    $cartToGet = NULL;
} else {
    $cartToGet = $_SESSION['cartID'];
}

//
// Active Customers
//
$customer = new killerCart\Customer();
$cs       = $customer->getCustomers($cartToGet);
if (empty($cs)) {
    ?>
    <div class="alert alert-block alert-info span6 offset3">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4><i class="icon-info-sign"></i>&nbsp;Sorry!</h4>
        There are no customers. Click <a href='?p=admin'>here</a> for admin home.
    </div>
    <?php
} else {
    $table = "
    <!-- Customers grid/table view -->
    <table class='table table-striped table-hover table-condensed'>
        <tr>
            <th>Actions</th>
            <th>Customer ID</th>
            <th>Company Name</th>
            <th>Customer Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Notes</th>
            <th>VisitorIP</th>
            <th>Last Login</th>
        </tr>";

    // Each customer
    foreach ($cs as $cid) {
        // Get customer info
        $c = $customer->getCustomerInfo($cid['customerID']);
        $table .= "<tr>
                <td>
                    <!-- Button to trigger Edit Customer modal -->
                    <button class='btn btn-mini customerEditBtn' value='" . $c['customerID'] . "'>
                        <i class='icon-edit'></i>&nbsp;Edit
                    </button>
                </td>
                <td>
                    <!-- Button to trigger Impersonate Customer -->
                    <a class='btn btn-mini' href='" . cartPublicUrl . "?p=account&customerID=" . $c['customerID'] . "' target='_blank'>
                        <i class='icon-play'></i>&nbsp;" . $c['customerID'] . "
                    </a>                
                </td>
                <td>" . $c['companyName'] . "</td>
                <td>" . $c['firstName'] . " " . $c['middleName'] . " " . $c['lastName'] . "</td>
                <td>" . $c['phone'] . "</td>
                <td>" . $c['email'] . "</td>
                <td>" . $c['notes'] . "</td>
                <td>" . $c['visitorIP'] . "</td>
                <td>" . $c['lastLoginDate'] . "</td>
            </tr>";
    }

    echo $table . '</table>';
}
?>