<div class='container'>

  <div class="page-header span12">
    <h1>Contact Us <small>Send us a message</small></h1>
  </div>

<?php
$showForm = TRUE;
if (!empty($_POST))
{
    $args = array(
        'contactName'=>FILTER_SANITIZE_SPECIAL_CHARS,
        'contactEmail'=>FILTER_SANITIZE_EMAIL,
        'contactMsg'=>FILTER_SANITIZE_SPECIAL_CHARS);
    $s = new killerCart\Sanitize();
    $san = $s->filterArray(INPUT_POST, $args);
    if ($san) {
       $showForm = FALSE;
    }
}
if (!$showForm)
{
    $email = new killerCart\Email();
    $cart = new killerCart\Cart($_SESSION['cartID']);
    $to = $cart->getCartContactEmail($cartID);
    $from = $san['contactEmail'];
    $replyto = $from;
    $cc = NULL;
    $bcc = NULL;
    $subject = "Contact from Cart";
    $body = "Name: " . $san['contactName'] . "<br /><br />Email: " . $san['contactEmail'] . "<br /><br />" . "Message: <br /><br />" . $san['contactMsg'];
    $email->sendEmail($to, $from, $replyto, $cc, $bcc, $subject, $body)
?>
    <div class="alert alert-success span6 offset2">
        <h2>Thank you for contacting us!</h2>
        Click <a href="<?php echo cartPublicUrl; ?>">here</a> to go back to the cart.
    </div>
<?php
    return;
}
?>
    
  <div class="alert alert-info span4 offset3">
    
    <?php
    $cart = new killerCart\Cart($_SESSION['cartID']);
    $sinfo = $cart->getCartInfo( $_SESSION['cartID'] );
    $saddress = $cart->getCartAddressInfo( $sinfo['addressID'] );
    
    echo $sinfo['cartName'] . "<br />";
    echo $saddress['line1'] . "<br />";
    if (!empty($saddress['line2'])) {
      echo $saddress['line2'] . "<br />";
    }
    if (!empty($saddress['line3'])) {
      echo $saddress['line3'] . "<br />";
    }
    echo $saddress['city'] . ", " . $saddress['stateProvinceCounty'] . " " . $saddress['zipPostcode'] . "<br />";;
    ?>
  </div>
  
    <form id="frmContactUs" action="?p=contact" method="POST">
        <div class='row'>
          <div class='span12'>        
            <h4>Use the form below to send us a message</h4>
            <table class="table">
              <tr>
                <td>Your Name</td>
                <td><input type="text" class="span5" id="contactName" name="contactName"/></td>
              </tr>
              <tr>
                <td>Your Email</td>
                <td><input type="text" class="span5" id="contactEmail" name="contactEmail"/></td>
              </tr>
              <tr>
                <td>Your Message</td>
                <td><textarea rows="10" class="span7" id="contactMsg" name="contactMsg"></textarea></td>
              </tr>
            </table>
            <div class="form-actions text-center">
              <button type="submit" class="btn btn-success"><i class="icon-check icon-white"></i>&nbsp;Send Message</button>
            </div>
          </div>
        </div>
    </form>
</div>

<?php
$pageJavaScript[] = "
<script>
$(document).ready(function() {

    $('#frmContactUs').validate({
        rules: {
            contactEmail: {
                email: true,
                required: true
            },
            contactName: {
                required: true
            },
            contactMsg: {
                required: true
            }
        }
    });
    
});
</script>
    ";