<div class='container'>

    <h1>Reports <small>Choose the cart and report to view</small></h1>
    <form method='POST'>
        <input type='hidden' name='p' value='<?php echo $_REQUEST['p']; ?>' />
        <input type='hidden' name='a' value='viewReport' />
        <?php
// Show Cart selection if Global admin
        if (!empty($_SESSION['user']['ACL']['global']['read'])) {
            ?>
            <select name='cartID'>
                <option value='ALL'<?php
                if (!isset($_REQUEST['cartID']) || $_REQUEST['cartID'] == 'ALL') {
                    echo ' selected';
                }
                ?>>All Carts</option>
                        <?php
                        $cart = new killerCart\KillerCart($_SESSION['cartID']);
                        foreach ($cart->getCartIDs('ALL') as $s) {
                            $thisCart = $cart->getCartInfo($s['cartID']);
                            if (isset($_REQUEST['cartID']) && $_REQUEST['cartID'] == $thisCart['cartID']) {
                                $selected = ' selected';
                            } else {
                                $selected = '';
                            }
                            echo "<option value='" . $thisCart['cartID'] . "'" . $selected . ">" . $thisCart['cartName'] . "</option>";
                        }
                        ?>
            </select>
            <?php
// Otherwise auto-select this cart
        } else {
            echo "<input type='hidden' name='cartID' value='" . $_SESSION['cartID'] . "' />";
        }
        ?>
        <!-- Report Choice -->
        <select name='reportName'>
            <option value='salesTotals'<?php
            if (!isset($_REQUEST['reportName']) || $_REQUEST['reportName'] == 'salesTotals') {
                echo ' selected';
            }
            ?>>Sales Totals</option>
            <option value='salesByProduct'<?php
                    if (isset($_REQUEST['reportName']) && $_REQUEST['reportName'] == 'salesByProduct') {
                        echo ' selected';
                    }
                    ?>>Sales By Product</option>
            <option value='declinedOrders'<?php
            if (isset($_REQUEST['reportName']) && $_REQUEST['reportName'] == 'declinedOrders') {
                echo ' selected';
            }
                    ?>>Declined Orders</option>
        </select>

        <!-- Daterange Choice -->
        <select name='dateRange'>
            <option value='1'<?php
            if (isset($_REQUEST['dateRange']) && $_REQUEST['dateRange'] == '1') {
                echo ' selected';
            }
            ?>>Last Day</option>
            <option value='7'<?php
            if (isset($_REQUEST['dateRange']) && $_REQUEST['dateRange'] == '7') {
                echo ' selected';
            }
            ?>>Last Week</option>
            <option value='30'<?php
                    if (!isset($_REQUEST['dateRange']) || $_REQUEST['dateRange'] == '30') {
                        echo ' selected';
                    }
                    ?>>Last Month</option>
            <option value='90'<?php
            if (isset($_REQUEST['dateRange']) && $_REQUEST['dateRange'] == '90') {
                echo ' selected';
            }
                    ?>>Last 3 Months</option>
            <option value='180'<?php
            if (isset($_REQUEST['dateRange']) && $_REQUEST['dateRange'] == '180') {
                echo ' selected';
            }
                    ?>>Last 6 Months</option>
            <option value='365'<?php
            if (isset($_REQUEST['dateRange']) && $_REQUEST['dateRange'] == '365') {
                echo ' selected';
            }
                    ?>>Last Year</option>
        </select>

        <!-- Update Report -->
        <button type='submit' class='btn btn-success'><i class='icon-ok-circle icon-white'></i>&nbsp;Update Report</button>
    </form>

</div>