-- MySQL Script generated by MySQL Workbench
-- 06/19/14 09:38:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AWOMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AWOMS` ;
CREATE SCHEMA IF NOT EXISTS `AWOMS` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `AWOMS` ;

-- -----------------------------------------------------
-- Table `brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brands` ;

CREATE TABLE IF NOT EXISTS `brands` (
  `brandID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `brandName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `brandActive` TINYINT(1) UNSIGNED NOT NULL,
  `brandLabel` VARCHAR(45) NOT NULL,
  `activeTheme` VARCHAR(45) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`brandID`, `brandName`, `brandActive`),
  UNIQUE INDEX `brandID_UNIQUE` (`brandID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `usergroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usergroups` ;

CREATE TABLE IF NOT EXISTS `usergroups` (
  `usergroupID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brandID` BIGINT(20) UNSIGNED NOT NULL,
  `usergroupName` VARCHAR(255) NULL,
  `usergroupActive` TINYINT(1) NULL,
  `parentUserGroupID` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`usergroupID`, `brandID`),
  UNIQUE INDEX `usergroupID_UNIQUE` (`usergroupID` ASC),
  INDEX `fk_usergroups_brands1_idx` (`brandID` ASC),
  INDEX `fk_usergroups_usergroups1_idx` (`parentUserGroupID` ASC),
  CONSTRAINT `fk_usergroups_brands1`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usergroups_usergroups1`
    FOREIGN KEY (`parentUserGroupID`)
    REFERENCES `usergroups` (`usergroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `userID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usergroupID` BIGINT UNSIGNED NOT NULL,
  `userName` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `userActive` TINYINT(1) NOT NULL,
  `userEmail` VARCHAR(255) NOT NULL,
  `passphrase` CHAR(128) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NULL,
  PRIMARY KEY (`userID`, `usergroupID`, `userName`, `userActive`, `userEmail`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  INDEX `fk_users_usergroups1_idx` (`usergroupID` ASC),
  CONSTRAINT `fk_users_usergroups1`
    FOREIGN KEY (`usergroupID`)
    REFERENCES `usergroups` (`usergroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;


-- -----------------------------------------------------
-- Table `articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles` ;

CREATE TABLE IF NOT EXISTS `articles` (
  `articleID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `articleName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `articleActive` TINYINT(1) UNSIGNED NOT NULL,
  `articleShortDescription` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `articleLongDescription` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `articleDatePublished` DATETIME NOT NULL,
  `articleDateLastReviewed` DATETIME NOT NULL,
  `articleDateLastUpdated` DATETIME NOT NULL,
  `articleDateExpires` DATETIME NULL DEFAULT NULL,
  `userID` BIGINT(20) UNSIGNED NOT NULL,
  `brandID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`articleID`, `articleActive`, `brandID`, `userID`),
  UNIQUE INDEX `articleID_UNIQUE` (`articleID` ASC),
  INDEX `fk_articles_users1_idx` (`userID` ASC),
  INDEX `fk_articles_brands1_idx` (`brandID` ASC),
  CONSTRAINT `fk_articles_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_brands1`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `refParentItemTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refParentItemTypes` ;

CREATE TABLE IF NOT EXISTS `refParentItemTypes` (
  `refParentItemTypeID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parentTypeLabel` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`refParentItemTypeID`),
  UNIQUE INDEX `refParentItemTypeID_UNIQUE` (`refParentItemTypeID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `bodyContents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bodyContents` ;

CREATE TABLE IF NOT EXISTS `bodyContents` (
  `bodyContentID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parentItemID` BIGINT(20) UNSIGNED NOT NULL,
  `parentItemTypeID` BIGINT(20) UNSIGNED NOT NULL,
  `bodyContentActive` TINYINT(1) UNSIGNED NOT NULL,
  `bodyContentDateModified` DATETIME NOT NULL,
  `bodyContentText` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `userID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`bodyContentID`, `parentItemID`, `bodyContentActive`, `parentItemTypeID`, `userID`),
  UNIQUE INDEX `commentBodyID_UNIQUE` (`bodyContentID` ASC),
  INDEX `fk_bodyContents_refParentItemTypes1_idx` (`parentItemTypeID` ASC),
  INDEX `fk_bodyContents_users1_idx` (`userID` ASC),
  CONSTRAINT `fk_bodyContents_refParentItemTypes1`
    FOREIGN KEY (`parentItemTypeID`)
    REFERENCES `refParentItemTypes` (`refParentItemTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodyContents_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

CREATE TABLE IF NOT EXISTS `categories` (
  `categoryID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `categoryActive` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`categoryID`, `categoryActive`),
  UNIQUE INDEX `categoryID_UNIQUE` (`categoryID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comments` ;

CREATE TABLE IF NOT EXISTS `comments` (
  `commentID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '	',
  `parentItemID` BIGINT(20) UNSIGNED NOT NULL COMMENT 'Comment belongs to parentID',
  `parentItemTypeID` BIGINT(20) UNSIGNED NOT NULL,
  `commentActive` TINYINT(1) UNSIGNED NOT NULL,
  `commentDatePublished` DATETIME NOT NULL,
  `commentDateLastUpdated` DATETIME NOT NULL,
  `userID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`commentID`, `parentItemID`, `commentActive`, `userID`, `parentItemTypeID`),
  UNIQUE INDEX `commentID_UNIQUE` (`commentID` ASC),
  INDEX `fk_comments_refParentItemTypes1_idx` (`parentItemTypeID` ASC),
  INDEX `fk_comments_users1_idx` (`userID` ASC),
  CONSTRAINT `fk_comments_refParentItemTypes1`
    FOREIGN KEY (`parentItemTypeID`)
    REFERENCES `refParentItemTypes` (`refParentItemTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `domains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domains` ;

CREATE TABLE IF NOT EXISTS `domains` (
  `domainID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `brandID` BIGINT(20) UNSIGNED NOT NULL,
  `domainName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `domainActive` TINYINT(1) UNSIGNED NOT NULL,
  `parentDomainID` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`domainID`, `brandID`, `domainName`, `domainActive`),
  UNIQUE INDEX `domainID_UNIQUE` (`domainID` ASC),
  INDEX `fk_domains_domains1_idx` (`parentDomainID` ASC),
  INDEX `fk_domains_brands1_idx` (`brandID` ASC),
  CONSTRAINT `fk_domains_domains1`
    FOREIGN KEY (`parentDomainID`)
    REFERENCES `domains` (`domainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domains_brands1`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `images` ;

CREATE TABLE IF NOT EXISTS `images` (
  `imageID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `imageName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `imageType` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `imageSize` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`imageID`),
  UNIQUE INDEX `imageID_UNIQUE` (`imageID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keywords` ;

CREATE TABLE IF NOT EXISTS `keywords` (
  `keywordID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`keywordID`, `keyword`),
  UNIQUE INDEX `keywordID_UNIQUE` (`keywordID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `refCategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refCategories` ;

CREATE TABLE IF NOT EXISTS `refCategories` (
  `parentItemID` BIGINT(20) UNSIGNED NOT NULL,
  `parentItemTypeID` BIGINT(20) UNSIGNED NOT NULL,
  `categoryID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`parentItemID`, `categoryID`, `parentItemTypeID`),
  INDEX `fk_table1_Categories1_idx` (`categoryID` ASC),
  INDEX `fk_refCategories_refParentItemTypes1_idx` (`parentItemTypeID` ASC),
  CONSTRAINT `fk_refCategories_refParentItemTypes1`
    FOREIGN KEY (`parentItemTypeID`)
    REFERENCES `refParentItemTypes` (`refParentItemTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Categories1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `categories` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `refImages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refImages` ;

CREATE TABLE IF NOT EXISTS `refImages` (
  `parentItemID` BIGINT(20) UNSIGNED NOT NULL,
  `parentItemTypeID` BIGINT(20) UNSIGNED NOT NULL,
  `imageID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`parentItemID`, `imageID`, `parentItemTypeID`),
  INDEX `fk_refArticlesImages_Images1_idx` (`imageID` ASC),
  INDEX `fk_refArticlesImages_refParentItemTypes1_idx` (`parentItemTypeID` ASC),
  CONSTRAINT `fk_refArticlesImages_Images1`
    FOREIGN KEY (`imageID`)
    REFERENCES `images` (`imageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refArticlesImages_refParentItemTypes1`
    FOREIGN KEY (`parentItemTypeID`)
    REFERENCES `refParentItemTypes` (`refParentItemTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `refKeywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refKeywords` ;

CREATE TABLE IF NOT EXISTS `refKeywords` (
  `parentItemID` BIGINT(20) UNSIGNED NOT NULL,
  `parentItemTypeID` BIGINT(20) UNSIGNED NOT NULL,
  `keywordID` BIGINT(20) UNSIGNED NOT NULL,
  `keywordCount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`parentItemID`, `parentItemTypeID`, `keywordID`),
  INDEX `fk_refParentItemKeywords_keywords1_idx` (`keywordID` ASC),
  INDEX `fk_refParentItemKeywords_refParentItemTypes1_idx` (`parentItemTypeID` ASC),
  CONSTRAINT `fk_refParentItemKeywords_keywords1`
    FOREIGN KEY (`keywordID`)
    REFERENCES `keywords` (`keywordID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refParentItemKeywords_refParentItemTypes1`
    FOREIGN KEY (`parentItemTypeID`)
    REFERENCES `refParentItemTypes` (`refParentItemTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pages` ;

CREATE TABLE IF NOT EXISTS `pages` (
  `pageID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pageName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `pageActive` TINYINT(1) UNSIGNED NOT NULL,
  `pageShortDescription` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `pageLongDescription` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `pageDatePublished` DATETIME NOT NULL,
  `pageDateLastReviewed` DATETIME NOT NULL,
  `pageDateLastUpdated` DATETIME NOT NULL,
  `pageDateExpires` DATETIME NULL,
  `userID` BIGINT(20) UNSIGNED NOT NULL,
  `brandID` BIGINT(20) UNSIGNED NOT NULL,
  `pageJavaScript` TEXT NULL,
  `pageShowTitle` TINYINT(1) NULL,
  PRIMARY KEY (`pageID`, `pageActive`, `brandID`, `userID`),
  UNIQUE INDEX `articleID_UNIQUE` (`pageID` ASC),
  INDEX `fk_articles_users1_idx` (`userID` ASC),
  INDEX `fk_pages_brands1_idx` (`brandID` ASC),
  CONSTRAINT `fk_pages_users10`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pages_brands1`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sessions` ;

CREATE TABLE IF NOT EXISTS `sessions` (
  `sessionID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brandID` BIGINT(20) UNSIGNED NOT NULL,
  `fingerprint` CHAR(128) NOT NULL,
  `setTime` CHAR(10) NOT NULL,
  `expiresTime` CHAR(10) NOT NULL,
  `visitorIP` CHAR(46) NOT NULL,
  `session` TEXT NOT NULL,
  PRIMARY KEY (`sessionID`, `brandID`, `fingerprint`),
  UNIQUE INDEX `sessionID_UNIQUE` (`sessionID` ASC),
  INDEX `fk_sessions_brands1_idx` (`brandID` ASC),
  UNIQUE INDEX `fingerprint_UNIQUE` (`fingerprint` ASC),
  CONSTRAINT `fk_sessions_brands1`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messageLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messageLog` ;

CREATE TABLE IF NOT EXISTS `messageLog` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `messageDateTime` DATETIME NOT NULL,
  `messageBrandID` BIGINT(20) UNSIGNED NOT NULL,
  `messageType` VARCHAR(45) NULL,
  `messageBody` TEXT NULL,
  `messageFile` VARCHAR(1000) NULL,
  `messageLine` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`, `messageDateTime`, `messageBrandID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_messageLog_brands1_idx` (`messageBrandID` ASC),
  CONSTRAINT `fk_messageLog_brands1`
    FOREIGN KEY (`messageBrandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acls` ;

CREATE TABLE IF NOT EXISTS `acls` (
  `brandID` BIGINT(20) UNSIGNED NULL,
  `usergroupID` BIGINT UNSIGNED NULL,
  `userID` BIGINT(20) UNSIGNED NULL,
  `controller` VARCHAR(45) NULL,
  `create` TINYINT(1) NULL,
  `read` TINYINT(1) NULL,
  `update` TINYINT(1) NULL,
  `delete` TINYINT(1) NULL,
  INDEX `fk_aclDefaults_usergroups1_idx` (`usergroupID` ASC),
  INDEX `fk_aclDefaults_users1_idx` (`userID` ASC),
  CONSTRAINT `fk_aclDefaults_brands10`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aclDefaults_usergroups10`
    FOREIGN KEY (`usergroupID`)
    REFERENCES `usergroups` (`usergroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aclDefaults_users10`
    FOREIGN KEY (`userID`)
    REFERENCES `users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menus` ;

CREATE TABLE IF NOT EXISTS `menus` (
  `menuID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brandID` BIGINT(20) UNSIGNED NOT NULL,
  `menuName` VARCHAR(45) NULL,
  `menuActive` TINYINT(1) NULL,
  PRIMARY KEY (`menuID`, `brandID`),
  UNIQUE INDEX `ID_UNIQUE` (`menuID` ASC),
  INDEX `fk_menus_brands2_idx` (`brandID` ASC),
  CONSTRAINT `fk_menus_brands2`
    FOREIGN KEY (`brandID`)
    REFERENCES `brands` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menuLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menuLinks` ;

CREATE TABLE IF NOT EXISTS `menuLinks` (
  `linkID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `menuID` BIGINT UNSIGNED NOT NULL,
  `sortOrder` TINYINT(2) NULL,
  `parentLinkID` BIGINT UNSIGNED NULL,
  `display` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `linkActive` TINYINT(1) NULL,
  PRIMARY KEY (`linkID`, `menuID`),
  UNIQUE INDEX `ID_UNIQUE` (`linkID` ASC),
  INDEX `fk_menus_menus1_idx` (`parentLinkID` ASC),
  INDEX `fk_menuLinks_menus1_idx` (`menuID` ASC),
  CONSTRAINT `fk_menus_menus1`
    FOREIGN KEY (`parentLinkID`)
    REFERENCES `menuLinks` (`linkID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuLinks_menus1`
    FOREIGN KEY (`menuID`)
    REFERENCES `menus` (`menuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rewriteMappings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewriteMappings` ;

CREATE TABLE IF NOT EXISTS `rewriteMappings` (
  `rewriteMappingID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aliasURL` VARCHAR(255) NULL,
  `actualURL` VARCHAR(255) NULL,
  `sortOrder` INT NULL,
  `domainID` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`rewriteMappingID`),
  UNIQUE INDEX `rewriteMappingID_UNIQUE` (`rewriteMappingID` ASC),
  INDEX `fk_rewriteMappings_domains1_idx` (`domainID` ASC),
  CONSTRAINT `fk_rewriteMappings_domains1`
    FOREIGN KEY (`domainID`)
    REFERENCES `domains` (`domainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
