<?php
echo '&nbsp;<small>Viewing selected order</small></h1></div><!--#page-header-->';

// Variables from order.php
?>

<!--BEGIN:#admin_order_edit_container-->
<div id="admin_order_edit_container" class="container">

    <?php
    // Inner Action Result Message
    if (!empty($_POST['ia'])) {
        ?>
        <div class='row'>
            <div class='alert alert-block alert-<?php echo $alertType; ?> span6 offset3 text-center'>
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>
                    <?php
                    if ($alertType == 'success') {
                        echo "<i class='icon-ok'></i>";
                    } else {
                        echo "<i class='icon-remove'></i>";
                    }
                    ?>
                    &nbsp;<?php echo $label; ?></h4>
            </div>
        </div>
        <?php
    }
    ?>

    <div class='row'>
        <div class='span8'>

            <!-- Order Table -->
            <table class='table table-striped table-hover table-bordered table-condensed'>
                <caption><h2>Order #<?php echo $orderID; ?> Details</h2></caption>
                <tr>
                    <td><strong>Order Date</strong></td>
                    <td><?php echo killerCart\Util::getServerDateTimeFromUTCDateTime($o['dateOrderPlaced']); ?></td>
                </tr>
                <tr>
                    <td><strong>Customer ID</strong></td>
                    <td><?php echo $o['customerID']; ?></td>
                </tr>

                <!-- Payment Method -->
                <tr>
                    <td><strong>Payment Method</strong></td>
                    <td>
                        <?php
                        // [x] ACL
                        if (empty($billingACL['read'])) {
                            echo 'Restricted';
                        } else {
                            ?>
                            <div class='span4'>
                                <table class='table table-condensed table-bordered'>
                                    <tr>
                                        <td>Type</td>
                                        <td>
                                            <?php
                                            if ($pmType == 'AMEX') {
                                                $img = 'amex_logo_mini.gif';
                                            } elseif ($pmType == 'VISA') {
                                                $img = 'visa_logo_mini.gif';
                                            } elseif ($pmType == 'MC') {
                                                $img = 'mastercard_logo_mini.gif';
                                            } elseif ($pmType == 'DISC') {
                                                $img = 'discover_logo_mini.gif';
                                            } elseif ($pmType == 'CHK') {
                                                $img = 'check_icon_mini.png';
                                            } elseif ($pmType == 'ECHK') {
                                                $img = 'echeck_logo_mini.gif';
                                            } elseif ($pmType == 'WIRE') {
                                                $img = 'echeck_logo_mini.gif';
                                            } elseif ($pmType == 'PAYP') {
                                                $img = 'paypal_logo_mini.gif';
                                            } elseif ($pmType == 'CASH') {
                                                $img = 'cash.png';
                                            } else {
                                                $img = 'unknown.png';
                                            }
                                            echo "<img src='../img/" . $img . "' data-toggle='tooltip' class='tooltip-on' title='" . $pmDesc . "'>";
                                            ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width='100px'>Number</td>
                                        <td>
                                            <button id='maskedNumber1' class='btn btn-mini'>
                                                <?php echo $number1masked; ?>
                                            </button>
                                            <button id='number1' class='btn btn-mini' style='display:none'>
                                                <?php echo $number1plain; ?>
                                            </button>
                                        </td>
                                    </tr>
                                    <?php
                                    if (!empty($number2)) {
                                        ?>
                                        <tr>
                                            <td>Number2</td>
                                            <td><?php echo $number2; ?></td>
                                        </tr>
                                        <?php
                                    }
                                    if (!empty($number3)) {
                                        ?>
                                        <tr>
                                            <td>Number3</td>
                                            <td><?php echo $number3; ?></td>
                                        </tr>
                                        <?php
                                    }
                                    if (!empty($expMonth)) {
                                        ?>
                                        <tr>
                                            <td>Expiration</td>
                                            <td><?php echo $expMonth . ' / ' . $expYear; ?></td>
                                        </tr>
                                        <?php
                                    }
                                    if ($pmNotes != '') {
                                        ?>
                                        <tr>
                                            <td>Other Details</td>
                                            <td><?php echo $pmNotes; ?></td>
                                        </tr>
                                        <?php
                                    }

                                    // @todo AVS / CVV results
                                    echo "
                                    <tr>
                                        <td>AVS Match</td>
                                        <td>" . $avsResult . "</td>
                                    </tr>
                                    
                                    <tr>
                                        <td>CVV Match</td>
                                        <td>" . $cvvResult . "</td>
                                    </tr>";
                                    ?>
                                </table>
                            </div>
                            <?php
                        } // End ACL
                        ?>
                    </td>
                </tr>

                <!-- Shipping Address -->
                <?php
                $customer = new killerCart\Customer();
                $sa       = $customer->getCustomerAddresses($customerID, $o['shippingAddressID']);
                $atype    = $sa['addressTypeCode'];
                $afirst   = $sa['firstName'];
                $alast    = $sa['lastName'];
                $aphone   = $sa['phone'];
                $aemail   = $sa['email'];
                $aline1   = $sa['line1'];
                $aline2   = $sa['line2'];
                $aline3   = $sa['line3'];
                $acity    = $sa['city'];
                $azip     = $sa['zipPostcode'];
                $astate   = $sa['stateProvinceCounty'];
                $acountry = $sa['country'];
                $anotes   = $sa['addressNotes'];
                ?>
                <tr>
                    <td>
                        <strong>Shipping Address</strong>
                        <br />Type: <?php echo $atype; ?>
                    </td>
                    <td>
                        <div class='span5'>
                            <table class='table table-condensed table-bordered'>
                                <tr>
                                    <td>Name</td>
                                    <td><?php echo $afirst . ' ' . $alast; ?></td>
                                </tr>                                
                                <tr>
                                    <td>Address</td>
                                    <td><?php echo $aline1; ?></td>
                                </tr>
                                <?php
                                if (!empty($aline2)) {
                                    ?>
                                    <tr>
                                        <td></td>
                                        <td><?php echo $aline2; ?></td>
                                    </tr>
                                    <?php
                                }
                                if (!empty($aline3)) {
                                    ?>
                                    <tr>
                                        <td></td>
                                        <td><?php echo $aline3; ?></td>
                                    </tr>
    <?php
}
?>
                                <tr>
                                    <td>City/State/Zip</td>
                                    <td><?php echo $acity . ', ' . $astate . ' ' . $azip; ?></td>
                                </tr>
                                <tr>
                                    <td>Country</td>
                                    <td><?php echo $acountry; ?></td>
                                </tr>
<?php
if (!empty($aphone)) {
    ?>
                                    <tr>
                                        <td>Phone</td>
                                        <td><?php echo $aphone; ?></td>
                                    </tr>
    <?php
}
if (!empty($anotes)) {
    ?>
                                    <tr>
                                        <td>Notes</td>
                                        <td><?php echo $anotes; ?></td>
                                    </tr>
    <?php
}
?>
                            </table>
                        </div>
                    </td>
                </tr>

                <!-- Delivery Status -->
                <tr class='<?php echo $deliveryClass; ?>'>
                    <td><strong>Delivery Status</strong></td>
                    <td>
                        <!--BEGIN:#admin_order_delivery_status_edit_form-->
                        <form id='admin_order_delivery_status_edit_form' class='form-horizontal' method="POST" action='<?php echo cartPublicUrl . 'admin/'; ?>'>
                            <input type="hidden" name="p" value="<?php echo $_REQUEST['p']; ?>" />
                            <input type="hidden" name="a" id="a" value="view_customer_order_single" />
                            <input type="hidden" name="s" value="3" />
                            <input type="hidden" name="oid" value="<?php echo $orderID; ?>" />
                            <select id='orderDeliveryStatusCode' name='orderDeliveryStatusCode' class='span2'<?php echo $enableOrderDeliveryStatus; ?>>
<?php
foreach ($order->getOrderDeliveryStatusCodes() as $osc) {
    if ($osc['deliveryStatusCode'] == $orderCurDeliveryStatusCode['deliveryStatusCode']) {
        $selected = ' selected';
    } else {
        $selected = '';
    }
    echo "<option value='" . $osc['deliveryStatusCode'] . "'" . $selected . ">" . $osc['deliveryStatusDescription'] . "</option>";
}
?>
                            </select>

                                <?php
                                // Update Button (only show if can use)
                                // [x] ACL
                                if ($enableOrderDeliveryStatus == '') {
                                    ?>
                                <button name='ia' value='update_orderDeliveryStatusCode' type='submit' class='btn btn-success btn-mini'>Update</button>                            
                                <?php
                            }

                            // User History
                            if (empty($orderCurDeliveryStatusCode['userIDReported'])) {
                                $username = 'System';
                            } else {
                                $user     = new killerCart\User();
                                $u        = $user->getUserInfo($orderCurDeliveryStatusCode['userIDReported']);
                                $username = $u['username'];
                            }
                            echo "<br /><small class='muted'>@ " . killerCart\Util::getServerDateTimeFromUTCDateTime($orderCurDeliveryStatusCode['dateReported']) . " by " . $username . "</small>";
                            ?>
                        </form>
                        <!--END:#admin_order_delivery_status_edit_form-->
                            <?php
                            // Results Message
                            if (!empty($_POST['ia'])) {
                                if ($_POST['ia'] == 'update_orderDeliveryStatusCode') {
                                    ?>
                                <div class='alert alert-success span2'>
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    <h4><i class="icon-ok"></i>&nbsp;Updated!</h4>
                                </div>
        <?php
    }
}
?>
                    </td>
                </tr>

                <!-- Order Status -->
                <tr class='<?php echo $orderClass; ?>'>
                    <td><strong>Order Status</strong></td>
                    <td>
                        <!--BEGIN:#admin_order_status_edit_form-->
                        <form id='admin_order_status_edit_form' class='form-horizontal' method="POST" action='<?php echo cartPublicUrl . 'admin/'; ?>'>
                            <input type="hidden" name="p" value="<?php echo $_REQUEST['p']; ?>" />
                            <input type="hidden" name="a" id="a" value="view_customer_order_single" />
                            <input type="hidden" name="s" value="3" />
                            <input type="hidden" name="oid" value="<?php echo $orderID; ?>" />
                            <select id='orderStatusCode' name='orderStatusCode' class='span2'<?php echo $enableOrderStatus; ?>>
<?php
foreach ($order->getOrderStatusCodes() as $osc) {
    if ($osc['orderStatusCode'] == $orderCurStatusCode['orderStatusCode']) {
        $selected = ' selected';
    } else {
        $selected = '';
    }
    echo "<option value='" . $osc['orderStatusCode'] . "'" . $selected . ">" . $osc['orderStatusDescription'] . "</option>";
}
?>
                            </select>
                                <?php
                                //
                                // DECIDE WHICH BUTTONS TO SHOW (Online processor only)
                                //
                            $allowChargeButton = false;
                                $allowVoidButton   = false;
                                $allowRefundButton = false;
                                // ACL: If allowed to change billing
                                if (!empty($billingACL['write'])) {
                                    if (empty($spg['gatewayOffline'])) {
                                        // Allow Charge Button if order authorized and shipping completed
                                        if ($orderCurStatusCode['orderStatusCode'] == 'ATH' && in_array($orderCurDeliveryStatusCode['deliveryStatusCode'],
                                                                                                        array('SHP', 'CMP'))) {
                                            // If order has amount to charge
                                            if ($o['totalOrderPrice'] > 0) {
                                                $allowChargeButton = true;
                                            }
                                        }

                                        // Allow Void Button (which triggers reversal/void) if order authorized/paid/complete and shipping cancelled/returned or completed
                                        // (allow shipping = completed in case of not returning or no shipping etc.)
                                        // @todo Time/Batch constraint
                                        if (in_array($orderCurStatusCode['orderStatusCode'], array('ATH', 'PD', 'CMP')) && in_array($orderCurDeliveryStatusCode['deliveryStatusCode'],
                                                                                                                                    array(
                                                    'SHP',
                                                    'CMP',
                                                    'CNC', 'RTN', 'PND'))) {
                                            // If order has amount to charge
                                            if ($o['totalOrderPrice'] > 0) {
                                                $allowVoidButton = true;
                                            }
                                        }

                                        // Allow Refund Button (which triggers return/refund) if order paid/completed and shipping cancelled/returned or completed
                                        // (allow shipping = completed in case of not returning or no shipping etc.)
                                        // @todo Time/Batch constraint
                                        if (in_array($orderCurStatusCode['orderStatusCode'], array('PD', 'CMP')) && in_array($orderCurDeliveryStatusCode['deliveryStatusCode'],
                                                                                                                             array('SHP',
                                                    'CMP',
                                                    'CNC',
                                                    'RTN', 'PND'))) {
                                            // If order has amount to charge
                                            if ($o['totalOrderPrice'] > 0) {
                                                $allowRefundButton = true;
                                            }
                                        }
                                    }

                                    // 
                                    // SHOW BUTTONS
                                    // 
                                    // Update Order Status Button
                                    if ($enableOrderStatus == '') {
                                        ?>
                                    <button name='ia' value='updateOrderStatusCode' type='submit' class='btn btn-success btn-mini'>
                                        Update
                                    </button>
        <?php
    }

    // Charge Button
    if ($allowChargeButton === true) {
        ?>
                                    <!-- Charge Customer Button -->
                                    <button name='ia' id='capturePayment' value='capturePayment' type='submit' class='btn btn-success btn-mini'>
                                        Charge Customer<br /><strong>$<?php echo $o['totalOrderPrice']; ?></strong>
                                    </button>
        <?php
    }

    // Void Button
    if ($allowVoidButton === true) {
        ?>
                                    <!-- Void Order Button -->
                                    <button name='ia' id='voidOrder' value='voidOrder' type='submit' class='btn btn-warning btn-mini'>
                                        Void Order
                                    </button>
        <?php
    }

    // Refund Button
    if ($allowRefundButton === true) {
        ?>
                                    <button name='ia' id='refundOrder' value='refundOrder' type='submit' class='btn btn-danger btn-mini'>
                                        Refund Order
                                    </button>
        <?php
    }
} // End ACL
// User History
if (empty($orderCurStatusCode['userIDReported'])) {
    $username = 'System';
} else {
    $user     = new killerCart\User();
    $u        = $user->getUserInfo($orderCurStatusCode['userIDReported']);
    $username = $u['username'];
}
echo "<br /><small class='muted'>@ " . killerCart\Util::getServerDateTimeFromUTCDateTime($orderCurStatusCode['dateReported']) . " by " . $username . "</small>";
?>
                        </form>

                        <!--END:#admin_order_status_edit_form-->

                    </td>
                </tr>

<?php
if (in_array($orderCurStatusCode['orderStatusCode'], array('PD', 'CMP', 'ARC'))) {
    $class = 'success';
    $date  = $o['dateOrderPaid'];
} else {
    $class = 'error';
    $date  = 'Unpaid';
}
?>
                <tr class='<?php echo $class; ?>'>
                    <td><strong>Date Order Paid</strong></td>
                    <td><?php echo $date; ?></td>
                </tr>
                <tr>
                    <td><strong>Total Order Price</strong></td>
                    <td>
                        <div class="input-prepend tooltip-on" data-toggle='tooltip' title='$<?php echo $o['totalOrderPrice']; ?>'>
                            <span class="add-on">$</span>
                            <input type='text' class='span2' disabled value='<?php echo $o['totalOrderPrice']; ?>'>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><strong>Other Order Details</strong></td>
                    <td><?php echo $o['orderNotes']; ?></td>
                </tr>
            </table>
        </div>

        <!-- Right Column -->
        <div class='span4'>
<?php
if (!in_array($orderCurStatusCode['orderStatusCode'], array('CNC', 'VD', 'RFN', 'DCL'))) {
    ?>
                <div class="alert alert-block alert-info">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <h4>Order Process</h4>
                    <br />
                    <ul class='unstyled'>
    <?php
    if (in_array($orderCurStatusCode['orderStatusCode'], array('ATH', 'PD', 'CMP', 'ARC'))) {
        $class = 'icon-ok-sign';
    } else {
        $class = 'icon-remove';
    }
    ?>
                        <li><i class='<?php echo $class; ?>'></i>&nbsp;Order Pre-Authorized</li>

    <?php
    // If shipping complete
    if (in_array($orderCurDeliveryStatusCode['deliveryStatusCode'], array('SHP', 'CMP', 'ARC'))) {
        $class = 'icon-ok-sign';
        // If shipping in-progress
    } elseif (in_array($orderCurDeliveryStatusCode['deliveryStatusCode'], array('PND', 'RDY', 'SPP'))) {
        $class = 'icon-remove';
        // If shipping cancelled etc.
    } else {
        $class = 'icon-exclamation-sign';
    }
    ?>
                        <li><i class='icon-question-sign'></i>&nbsp;Verify AVS/CVV Match</li>
                        <li><i class='<?php echo $class; ?>'></i>&nbsp;Update products delivery status</li>

    <?php
    if (in_array($orderCurStatusCode['orderStatusCode'], array('PD', 'CMP', 'ARC'))) {
        $class = 'icon-ok-sign';
    } else {
        $class = 'icon-remove';
    }
    ?>
                        <li><i class='<?php echo $class; ?>'></i>&nbsp;Charge customer for full amount</li>
                        <li><i class='<?php echo $class; ?>'></i>&nbsp;Order complete
                    </ul>
                </div>
    <?php
}
?>
        </div>

    </div>

    <p>&nbsp;</p>

    <table class='table table-hover table-bordered table-condensed'>
        <caption><h2>Order Product Details</h2></caption>    
        <tr>
            <th>Product ID</th>
            <th>Name</th>
            <th>Quantity</th>
            <th>Order Comments</th>
            <th>Delivery Status</th>
            <th>Price</th>
        </tr>

<?php
$order_product_subtotal          = 0;
$order_product_delivery_subtotal = 0;
$cartID                         = $_SESSION['cartID'];
$orderTaxAmount                  = $order->calcOrderTax($cartID, $orderID);
$product                         = new killerCart\Product();
foreach ($order->getOrderProducts($orderID) as $op) {
    $pInfo                       = $product->getProductInfo($op['productID']);
    $pInfo['deliveryStatusCode'] = $order->getOrderProductCurrentDeliveryInfo($orderID, $pInfo['productID']);
    $order_product_subtotal += $pInfo['price'] * $op['quantity'];
    $order_product_delivery_subtotal += $pInfo['deliveryStatusCode']['deliveryPrice'];
    if (in_array($pInfo['deliveryStatusCode']['deliveryStatusCode'], array('SHP', 'CMP'))) {
        $class = 'success';
    } elseif (in_array($pInfo['deliveryStatusCode']['deliveryStatusCode'], array('RDY', 'SPP', 'ARC'))) {
        $class = 'info';
    } elseif (in_array($pInfo['deliveryStatusCode']['deliveryStatusCode'], array('PND'))) {
        $class = 'warning';
    } else {
        $class = 'error';
    }

    // Product Options
    $options      = $order->getOrderProductsOptions($orderID, $op['productID']);
    $optionsPrice = 0;
    $optionMsg    = '';
    if (!empty($options)) {
        $optionMsg    = '<h6>Options:</h6>';
        $lastOptionID = null;
        foreach ($options as $option) {
            $optionID    = $option['productOptionCustomID'];
            $choiceID    = $option['productOptionChoiceCustomID'];
            $choice      = $product->getProductOptionsChoicesCustom($optionID, $choiceID);
            $choiceName  = $choice['choiceValueCustom'];
            $choicePrice = $choice['choicePriceCustom'];
            $optionsPrice += $choicePrice;
            if (!empty($lastOptionID) && $lastOptionID != $optionID) {
                $productOptions = $product->getProductOptionsCustom($cartID, $op['productID'], $optionID);
                $optionName     = $productOptions['optionNameCustom'];
                $optionMsg .= '</ul><small>' . $optionName . ':</small><ul>';
            } elseif (empty($lastOptionID)) {
                $productOptions = $product->getProductOptionsCustom($cartID, $op['productID'], $optionID);
                $optionName     = $productOptions['optionNameCustom'];
                $optionMsg .= '<small>' . $optionName . ':</small><ul>';
            }
            $optionMsg .= '<li>' . $choiceName . ' ($' . $choicePrice . ')</li>';
            $lastOptionID = $optionID;
        }
        $optionMsg .= '</ul>';
        $order_product_subtotal += ($optionsPrice * $op['quantity']);
    }

    echo "<tr class='" . $class . "'>
				<td>" . $pInfo['productID'] . "</td>
				<td>" . $pInfo['productName'] . $optionMsg . "</td>
                <td>" . $op['quantity'] . "</td>
				<td>" . $op['comments'] . "</td>
				<td>";
    // Delivery Status
    ?>
            <!--BEGIN:#admin_order_productXXX_delivery_status_edit_form-->
            <form id='admin_order_product<?php echo $pInfo['productID']; ?>_delivery_status_edit_form' class='form-horizontal' method="POST" action='<?php echo cartPublicUrl . 'admin/'; ?>'>
                <input type="hidden" name="p" value="<?php echo $_REQUEST['p']; ?>" />
                <input type="hidden" name="a" id="a" value="view_customer_order_single" />
                <input type="hidden" name="s" value="3" />
                <input type="hidden" name="oid" value="<?php echo $order->id; ?>" />
                <input type="hidden" name="order_productID" value="<?php echo $pInfo['productID']; ?>" />
                <select name='order_product_deliveryStatusCode' class='span2'<?php echo $enableProductDeliveryStatus; ?>>
    <?php
    foreach ($order->getOrderDeliveryStatusCodes() as $osc) {
        if ($osc['deliveryStatusCode'] == $pInfo['deliveryStatusCode']['deliveryStatusCode']) {
            $selected = ' selected';
        } else {
            $selected = '';
        }
        echo "<option value='" . $osc['deliveryStatusCode'] . "'" . $selected . ">" . $osc['deliveryStatusCode'] . "&nbsp;-&nbsp;" . $osc['deliveryStatusDescription'] . "</option>";
    }
    ?>
                </select>
                    <?php
                    // User History
                    if (empty($pInfo['deliveryStatusCode']['userIDReported'])) {
                        $username = 'System';
                    } else {
                        $user     = new killerCart\User();
                        $u        = $user->getUserInfo($pInfo['deliveryStatusCode']['userIDReported']);
                        $username = $u['username'];
                    }
                    echo "<br /><small class='muted'>@ " . killerCart\Util::getServerDateTimeFromUTCDateTime($pInfo['deliveryStatusCode']['dateReported']) . " by " . $username . "</small>";
                    ?>
                <?php
                // Results message if updated
                if (!empty($_POST['ia'])) {
                    if ($_POST['ia'] == 'update_order_product_delivery') {
                        if ($_POST['order_productID'] == $pInfo['productID']) {
                            ?>
                            <div class='clearfix'></div>
                            <div class='alert alert-success span2'>
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <h4><i class="icon-ok"></i>&nbsp;Updated!</h4>
                            </div>
                <?php
            }
        }
    }
    ?>
                </td>
                <!-- Price -->
                <td>
                    <div class="input-prepend tooltip-on" data-toggle='tooltip' title='$<?php echo $pInfo['price'] . ' per unit'; ?>'>
                        <span class="add-on">$</span>
                        <input type='text' class='span1' value='<?php
            echo killerCart\Util::getFormattedNumber(($pInfo['price'] + $optionsPrice) * $op['quantity']);
            ?>' disabled>
                    </div>
                    <br />
                    <div class="input-prepend tooltip-on" data-toggle="tooltip" title="Delivery Price">
                        <span class="add-on">$</span>
                        <input type="text" id="order_product_deliveryPrice" name="order_product_deliveryPrice" placeholder='S/H' value="<?php echo killerCart\Util::getFormattedNumber($pInfo['deliveryStatusCode']['deliveryPrice']); ?>" class="span1"<?php echo $enableProductDeliveryStatus; ?> />
                    </div>
                    <br />
    <?php
    // Update Shipping Button
    // [x] ACL
    if ($enableProductDeliveryStatus == '') {
        ?>
                        <button name='ia' value='update_order_product_delivery' type='submit' class='btn btn-success btn-mini'>Update</button>
                        <?php
                    }
                    ?>
            </form>
            <!--END:#admin_order_productXXX_delivery_status_edit_form-->
            </td>
            </tr>
    <?php
}
if ($o['dateOrderPaid'] != '') {
    $class = 'success';
} else {
    $class = 'error';
}
?>
        <tr class='<?php echo $class; ?>'>
            <td colspan='4' style='background-color:#ccc;'>&nbsp;</td>
            <td>Sub-total</td>
            <td><strong>$<?php echo killerCart\Util::getFormattedNumber($order_product_subtotal); ?></strong></td>
        </tr>
        <tr class='<?php echo $class; ?>'>
            <td colspan='4' style='background-color:#ccc;'>&nbsp;</td>
            <td>Delivery</td>
            <td><strong>$<?php echo killerCart\Util::getFormattedNumber($order_product_delivery_subtotal); ?></strong></td>
        </tr>
        <tr class='<?php echo $class; ?>'>
            <td colspan='4' style='background-color:#ccc;'>&nbsp;</td>
            <td>Tax</td>
            <td><strong>$<?php echo killerCart\Util::getFormattedNumber($orderTaxAmount); ?></strong></td>
        </tr>
        <tr class='<?php echo $class; ?>'>
            <td colspan='4' style='background-color:#ccc;'>&nbsp;</td>
            <td>Total</td>
            <td><strong>$
<?php
echo killerCart\Util::getFormattedNumber($order_product_subtotal + $order_product_delivery_subtotal + $orderTaxAmount);
?>
                </strong></td>
        </tr>
    </table>


    <p>&nbsp;</p>

    <table class='table table-hover table-bordered'>
        <caption><h2>Order Changelog</h2></caption>    
        <tr>
            <th>Date</th>
            <th>Action</th>
            <th>User</th>
            <th>New Value</th>
        </tr>

<?php
foreach ($order->getOrderChangelog() as $v) {
    echo "<tr>
				<td>" . killerCart\Util::getServerDateTimeFromUTCDateTime($v['dateReported']) . "</td>";
    // Action
    if ($v['history'] == 'codh') {
        $action = 'Delivery Status';
    } elseif ($v['history'] == 'cosh') {
        $action = 'Order Status';
    }
    // User
    if (empty($v['userIDReported'])) {
        $username = 'System';
    } else {
        $user     = new killerCart\User();
        $u        = $user->getUserInfo($v['userIDReported']);
        $username = $u['username'];
    }
    echo "<td>" . $action . "</td>";
    echo "<td>" . $username . "</td>";
    echo "<td>" . $v['code'] . "</td>";
    echo "</tr>";
}
?>
    </table>

<?php
if (strstr($spg['gatewayName'], 'Mercury') && $order_product_subtotal > 0) {
    ?>
        <p>&nbsp;</p>

        <div class="span12" style="overflow:auto">
            <center><h2>MercuryPay Changelog</h2></center>
            <table class='table table-hover table-bordered table-condensed'>
                <tr>
                    <th>Date</th>
                    <th>Action</th>
                    <th>Amount</th>
                    <th>Code</th>
                    <th>Status</th>
                    <th>TextResponse</th>
                    <th>Message</th>
                    <th>AVS</th>
                    <th>CVV</th>
                    <th>authCode</th>
                    <th>acqRefData</th>
                    <th>refNo</th>
                    <th>processData</th>
                    <th>frequency</th>
                    <th>recordNo</th>
                </tr>
    <?php
    $mp = new killerCart\MercuryPay();
    foreach ($mp->getMercuryPayChangelog($orderID, $customerID) as $m) {
        echo "<tr>
            <td>" . killerCart\Util::getServerDateTimeFromUTCDateTime($m['dateReported']) . "</td>
            <td>" . $m['action'] . "</td>
            <td>" . $m['amount'] . "</td>
            <td>" . $m['returnCode'] . "</td>
            <td>" . $m['returnStatus'] . "</td>
            <td>" . $m['returnTextResponse'] . "</td>
            <td>" . $m['returnMessage'] . "</td>
            <td>" . $m['avsResult'] . "</td>
            <td>" . $m['cvvResult'] . "</td>
            <td>" . $m['authCode'] . "</td>
            <td>" . $m['acqRefData'] . "</td>
            <td>" . $m['refNo'] . "</td>
            <td>" . $m['processData'] . "</td>
            <td>" . $m['frequency'] . "</td>
            <td>" . $m['recordNo'] . "</td>
        </tr>";
    }
    ?>
            </table>
        </div>
    <?php
}
?>

</div>
<!--END:#admin_order_edit_container-->