<div class='container'>
    <div class="page-header">
        <h1>Product Category Management<small>&nbsp;<?php echo "Total (" . $categoryCount['All'] . "), Active (" . $categoryCount['Active'] . "), Inactive (" . $categoryCount['Inactive'] . ")"; ?></small></h1>
    </div>
    <div class='row'>
        <div class='span4'>

            <!-- Button for Products Listing -->
            <a href="<?php echo cartPublicUrl; ?>admin/?p=product" role="button" class="btn" >
                <i class='icon-barcode'></i>&nbsp;Products
            </a>

            <!-- Button to trigger modal -->
            <a href="#newCategoryModal" role="button" class="btn" data-toggle="modal">
                <i class='icon-plus'></i>&nbsp;Add New Product Category
            </a>
        </div>
        
        <div class='span8'>
            
            <!-- View selection -->
            <div class='pull-right'>
                
                <div class='row'>
                    <div class='span5'>

                        <div class='btn-group' data-toggle='buttons-checkbox' style='padding-top:5px;'>
                            <button id='btnActiveView' class='btn btn-mini tooltip-on' value='active' data-toggle='tooltip' title='Active'>
                                <i class='icon-star'></i>
                            </button>

                            <button id='btnInactiveView' class='btn btn-mini tooltip-on' value='inactive' data-toggle='tooltip' title='Inactive'>
                                <i class='icon-star-empty'></i>
                            </button>
                        </div>

                        <div class='btn-group' data-toggle='buttons-radio' style='padding-top:5px;'>
                            <button id='btnThumbView' class='selView btn btn-mini tooltip-on' value='thumb' data-toggle='tooltip' title='Thumbnail View'>
                                <i class='icon-th-large'></i>
                            </button>

                            <button id='btnGridView' class='selView btn btn-mini tooltip-on' value='grid' data-toggle='tooltip' title='Grid View'>
                                <i class='icon-list'></i>
                            </button>
                        </div>

                    </div>
                    
                    <div class='span3'>

                        <div class='input-prepend input-append'>
                            <span class='add-on tooltip-on' data-toggle='tooltip' title='Product Category Filter'><i class='icon-search'></i></span>
                            <input id='categoryFilter' type='text' class='span2' data-provide='typeahead' autocomplete='off' />
                            <button class='btn btnFilterResults' type='button' class='btn'>Search</button>
                        </div>
                
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>