<!-- /***** ADD NEW PRODUCT CATEGORY FORM *****/ -->
<form id="frm_admin_new_category" class="form-horizontal" method="POST">
    <div id="newCategoryModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newCategoryModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times</button>
            <h3 id="newCategoryModalLabel">Add New Product Category</h3>
        </div>
        <div class="modal-body">

            <!-- Results -->
            <div id='results'></div>
            
            <!-- Cart Owner -->
            <div class="control-group">
                <label class="control-label" for="category_cartID">Cart Owner</label>
                <div class="controls">
                    <select id="category_cartID" name="category_cartID">
                        <?php
                        $cart = new killerCart\Cart($_SESSION['cartID']);
                        foreach ($cart->getCartIDs('All') as $k => $v) {
                            // ACL Check
                            if ($_SESSION['groupID'] != 1
                                    && $v['cartID'] != $_SESSION['cartID']) {
                                continue;
                            }
                            $s = $cart->getCartInfo($v['cartID']);
                            if ($s['cartActive'] == 0) {
                                $active = ' (Inactive)';
                            } else {
                                $active = '';
                            }
                            ?>
                            <option value='<?php echo $s['cartID']; ?>'><?php echo $s['cartName'].$active; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <!-- Parent Category -->
            <div class="control-group">
                <label class="control-label" for="category_parentID">Parent Category</label>
                <div class="controls">
                    <div id='category_parentID_dynamic'><span class='muted'>(Optional) Select cart first</span></div>
                </div>
            </div>

            <!-- Category Name -->
            <div class="control-group">
                <label class="control-label" for="categoryName"><strong>*Category Name</strong></label>
                <div class="controls">
                    <input type="text" id="categoryName" name="categoryName" placeholder="Enter Category Name">
                </div>
            </div>

            <!-- Category Code -->
            <div class="control-group">
                <label class="control-label" for="category_code">Category Code</label>
                <div class="controls">
                    <input type="text" id="category_code" name="category_code" placeholder="Code" maxlength="7" class='span1' />
                    <br />
                    <span class="muted">Code will be automatically generated if not entered</span>
                </div>
            </div>

            <!-- Description (Public) -->
            <div class="control-group">
                <label class="control-label" for="category_descriptionPublic">
                    <a href='#' class='tooltip-on' data-toggle='tooltip' title='Optional public category description that is viewable by anyone'>
                        <i class='icon-question-sign'></i>
                    </a>
                    &nbsp;Description (Public)
                </label>
                <div class="controls">
                    <textarea id="category_descriptionPublic" name="category_descriptionPublic" placeholder="Enter Public Description" rows='5' class='span3'></textarea>
                </div>
            </div>
            
            <!-- Description (Private) -->
            <div class="control-group">
                <label class="control-label" for="category_descriptionPrivate">
                    <a href='#' class='tooltip-on' data-toggle='tooltip' title='Optional private category description that is only viewable in the management portal'>
                        <i class='icon-question-sign'></i>
                    </a>
                    &nbsp;Description (Private)</label>
                <div class="controls">
                    <textarea id="category_descriptionPrivate" name="category_descriptionPrivate" placeholder="Enter Private Description" rows='5' class='span3'></textarea>
                </div>
            </div>

            <!-- Taxable -->
            <div class="control-group">
                <label class="control-label" for="category_taxable">
                    Taxable
                </label>
                <div class="controls">
                    <select name='category_taxable' class='span2'>
                        <option value='1' selected>Taxable</option>
                        <option value='0'>Nontaxable</option>
                    </select>
                </div>
            </div>

            <!-- Privacy -->
            <div class="control-group">
                <label class="control-label" for="category_privacy">
                    Privacy
                </label>
                <div class="controls">
                    <select id='category_privacy' name='category_privacy' class='span2'>
                        <option value='0' selected>Public</option>
                        <option value='1'>Private</option>
                    </select>
                </div>
            </div>
            
            <!-- Show Price -->
            <div class="control-group">
                <label class="control-label" for="category_showPrice">
                    <a href='#' class='tooltip-on' data-toggle='tooltip' title='Option to show or hide price on view cart and checkout'>
                        <i class='icon-question-sign'></i>
                    </a>&nbsp;
                    Show Price
                </label>
                <div class="controls">
                    <select id='category_showPrice' name='category_showPrice' class='span2'>
                        <option value='1' selected>Yes</option>
                        <option value='0'>No</option>
                    </select>
                </div>
            </div>

        </div>

        <div class="modal-footer">
            <input type="hidden" name="p" value="<?php echo $_REQUEST['p']; ?>" />
            <input type='hidden' name='m' value='ajax' />
            <input type='hidden' name='a' value='edit_category' />
            <input type='hidden' name='s' value='2' />
            <button id='createCategoryCloseBtn' class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id='createCategoryBtn' type="button" class="btn btn-success">
                <i class='icon-ok-sign icon-white'></i>&nbsp;Add New Category
            </button>
        </div>

    </div><!--#div_admin_new_category-->

</form><!--#frm_admin_new_category-->

<?php
$pageJavaScript[] = "
    <script type='text/javascript'>
        $(document).ready(function() {
        
            // Admin :: Product Categories :: Select cart to generate parent category select list
            $('#frm_admin_new_category #category_cartID').change(function() {
                if ($(this).val()) {
                    $('#frm_admin_new_category #category_parentID').removeAttr('disabled');
                    var get_categoryIDs = $.ajax({
                        data: {m: 'ajax',
                            a: 'getCategories',
                            cartID: $(this).val()}
                    })
                            .done(function(results) {
                        $('#category_parentID_dynamic').html(results);
                    })
                            .fail(function(msg) {
                        alert('Error:' + msg);
                    })
                            .always(function() {
                    });
                }
                else {
                    $('#frm_admin_new_category #category_parentID').attr('disabled', 'disabled');
                }
            });
            $('#frm_admin_new_category #category_cartID').trigger('change');
            
            // Admin :: Product Category :: New category form validation
            $('#frm_admin_new_category').validate({
                rules: {
                    category_cartID: 'required',
                    categoryName: 'required',
                    category_code: {
                        maxlength: 7
                    }
                }
            });
            
            // Admin :: Product Category :: New Category Modal :: Create Category
            $('#createCategoryBtn').click(function() {
                var v = $('#frm_admin_new_category').valid();
                if (v === false) {
                    alert('One or more fields on the parent form did not pass validation. Please check your fields and try again.');
                    return false;
                }
                var BTN = $(this);
                var oldHtml = BTN.html();
                BTN.prop('disabled', true).html('<i class=\'icon-refresh\'></i>&nbsp;Saving...');
                var go = $.ajax({
                    type: 'POST',
                    url: '" . cartPublicUrl . "admin/?p=category',
                    data: $('#frm_admin_new_category').serialize()
                })
                .done(function(results) {
                    //$('#theRest').addClass('hidden');
                    $('#results').html(results);
                    BTN.html('<i class=\'icon-ok icon-white\'></i>&nbsp;Done!');
                    delayedRefresh();
                })
                .fail(function(msg) {
                    alert('Error: ' + msg);
                })
                .always(function() {
                });
            });
            
            // Admin :: Product Category :: Edit Product Category Modal :: Close :: Refresh Page (if needed)
            $('#createCategoryCloseBtn').click(function() {
                var refresh = $('#results').html();
                if (refresh != '') {
                    location.reload();
                }
            });

        });
    </script>";