<!DOCTYPE html>
<!--[if lt IE 7]>      <html class='no-js lt-ie9 lt-ie8 lt-ie7'> <![endif]-->
<!--[if IE 7]>         <html class='no-js lt-ie9 lt-ie8'> <![endif]-->
<!--[if IE 8]>         <html class='no-js lt-ie9'> <![endif]-->
<!--[if gt IE 8]><!--> <html class='no-js'> <!--<![endif]--><html>
    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
        <meta http-equiv="Content-Language" content="en-us">
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <meta name='viewport' content='width=device-width'>
        <meta name="keywords" content="Goin' Postal, UPS, FedEx, UPS Cart, Shipping Franchise, UPS Cart Franchise, Franchises, Business Opportunities, Pak Mail Franchise, Postal Annex Franchise, Post Net Franchise, Post Office, Shipping, MailBoxes, private Mailboxes, Mail Forwarding">
        <meta name="Description" content="Goin' Postal is your sensible alternative to a UPS Cart Franchise, a FedEx Cart, Pak Mail, Post Net, or Postal Annex Franchise.">

        <title>Goin' Postal.&nbsp;Your local FedEx Cart, UPS Cart, and United States Post Office Alternative.</title>

        <link href="https://www.goinpostal.com/goinpostal.css" rel="stylesheet" type="text/css">

        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <!-- Must be between reg and responsive bootstrap -->
        <style>
            body {
                padding-bottom: 140px; /* 40/60 */
            }
        </style>
        <link rel="stylesheet" type="text/css" href="css/cart_style.php?privateDir=<?php echo cartPrivateDir; ?>&theme=<?php echo $cart->session['cartTheme']; ?>" />
        <script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body class='gpBody'>
        <div align="center">
            <center>
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111">
                    <tr>
                        <td width="964" height="111" class="logo-image">
                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td width="10%" height="111">     </td>
                                    <td width="90%" align="left" valign="bottom">      <ul>
                                            <div id="menu">
                                                <li><a href="https://www.goinpostal.com/owners/">Owner's Home</a></li>
                                                <li><a href="https://www.goinpostal.com/owners/cart_info.php">Cart Info</a></li>
                                                <li><a href="https://www.goinpostal.com/cart/?p=home">Owner's Cart</a></li>
                                                <li><a href="https://www.goinpostal.com/cart/?p=account&a=logout">Log Out</a></li>
                                                <li><a href="http://www.goinpostal.com/">Home</a></li>
                                                <li>
                                                    <a href='<?php echo cartPublicUrl . '?p=cart'; ?>'>
                                                        <i class="icon-shopping-cart icon-white"></i>
                                                        &nbsp;View Cart<?php echo " (" . $cartItemQty . ")"; ?>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="<?php echo cartPublicUrl; ?>?p=checkout">
                                                        <i class="icon-gift icon-white"></i>
                                                        &nbsp;Checkout
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="<?php echo cartPublicUrl; ?>?p=account">
                                                        <i class="icon-user icon-white"></i>
                                                        &nbsp;<?php echo $_SESSION['cInfo']['username']; ?>
                                                    </a>
                                                </li>
                                            </div>
                                        </ul></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </center>
        </div>

        <div class='clearfix'></div>

        <!-- Page Body -->
        <div class='container'>
            <div class='row'>
                <div class='span10 offset1 gpPageBody gradWrap'>

                    <!-- Breadcrumbs -->
                    <ul class="breadcrumb">
                        <li><a href="<?php echo cartPublicUrl . '?p=home'; ?>">Cart Home</a> <span class="divider">/</span></li>
                            <?php
                            // View Cart
                            if (empty($_REQUEST['p']) || $_REQUEST['p'] == 'cart') {
                                echo '<li class="active">View Cart</li>';
                                // Checkout
                            } elseif ($_REQUEST['p'] == 'checkout') {
                                echo '<li class="active">Checkout</li>';
                                // Account
                            } elseif ($_REQUEST['p'] == 'account') {
                                echo '<li class="active">My Account</li>';
                                // (Home) All Categories
                            } elseif ($_REQUEST['p'] == 'home') {
                                echo '<li class="active">All Categories</li>';
                                // Category / Product
                            } else {
                                if (!empty($_REQUEST['productID'])) {
                                    $category = new killerCart\Product_Category();
                                    $c        = $category->getCategoryInfo($p['categoryID']);
                                }
                                if (!empty($c['parentCategoryID'])) {
                                    // Is child category, need parent(s) breadcrumb
                                    $gotParent  = FALSE;
                                    $id         = NULL;
                                    $childBread = '';
                                    while ($gotParent === FALSE) {
                                        // First lookup: parent of this CID
                                        if (empty($id)) {
                                            $id = $c['parentCategoryID'];
                                            $tc = $c;
                                            continue;
                                        } else {
                                            // Next: Parent of this CID
                                            $id = $tc['parentCategoryID'];
                                            $tc = $category->getCategoryInfo($id);
                                        }
                                        // Found parent
                                        if (empty($tc['parentCategoryID'])) {
                                            $gotParent   = TRUE;
                                            $parentBread = "<li><a href='" . cartPublicUrl . "?p=category&categoryID=" . $tc['categoryID'] . "'>" . $tc['categoryName'] . "</a></li>";
                                        } else {
                                            // Still child
                                            $childBread = "&nbsp;<span class='divider'>/</span>&nbsp;<a href='" . cartPublicUrl . "?p=category&categoryID=" . $tc['categoryID'] . "'>" . $tc['categoryName'] . "</a>" . $childBread;
                                        }
                                    }
                                    echo $parentBread . "<li>" . $childBread . "</li>";
                                    if (empty($_REQUEST['productID'])) {
                                        echo "<li class='active'>&nbsp;<span class='divider'>/</span>&nbsp;" . $c['categoryName'] . "</li>";
                                    } else {
                                        echo "<li>&nbsp;<span class='divider'>/</span>&nbsp;<a href='" . cartPublicUrl . "?p=category&categoryID=" . $c['categoryID'] . "'>" . $c['categoryName'] . "</a></li>";
                                    }
                                } else {
                                    // Is parent category, no sub-categories breadcrumbs
                                    // Product page = category clickable
                                    if (!empty($_REQUEST['productID'])) {
                                        echo "<li class='active'><a href='" . cartPublicUrl . "?p=category&categoryID=" . $c['categoryID'] . "'>" . $c['categoryName'] . "</a></li>";
                                    } else {
                                        // Category page = category not-clickable
                                        echo '<li class="active">' . $c['categoryName'] . '</li>';
                                    }
                                }
                                // Chosen Product
                                if (!empty($_REQUEST['productID'])) {
                                    echo "<li class='active'>&nbsp;<span class='divider'>/</span>&nbsp;" . $p['productName'] . "</li>";
                                }
                            }
                            ?>
                    </ul>
                    <!-- End header -->