<div id='cart_admin_home_container' class='container'>
    <div class="page-header">
        <h1>Admin Test <small>Server requirements and health tests</small></h1>
    </div>
    
    <div class="row">
        <span class="alert alert-info span7 offset2">
            <h2>Test Results:</h2>
        <ul>
        <?php
        echo "<li>Mcrypt: ";
        if (!defined("MCRYPT_MODE_CFB"))
        {
            echo "<span style='color: red;'>Fail</span>";
        } else {
            echo "<span style='color: green;'>Pass</span>";
        }
        echo "</li>";
        
        echo "<li>Soap: ";
        if (!defined("SOAP_1_1"))
        {
            echo "<span style='color: red;'>Fail</span>";
        } else {
            echo "<span style='color: green;'>Pass</span>";
        }
        echo "</li>";
        
        /**
         * Tests the ability to 1) create pub/priv key pair 2) extract pub/priv keys 3) encrypt plaintext using keys 4) decrypt using keys
         * 
         * @return boolean|string False if fails, string if success
         */
        function testOpenSSL($opensslConfigPath = NULL)
        {
            if ($opensslConfigPath == NULL)
            {
                $opensslConfigPath = OPENSSL_CONFIG;
            }
            $config = array(
                "config" => $opensslConfigPath,
                "digest_alg" => "sha512",
                "private_key_bits" => 4096,
                "private_key_type" => OPENSSL_KEYTYPE_RSA,
            );

            $res = openssl_pkey_new($config);
            if (empty($res)) {return false;}

            // Extract the private key from $res to $privKey
            openssl_pkey_export($res, $privKey, NULL, $config);

            // Extract the public key from $res to $pubKey
            $pubKey = openssl_pkey_get_details($res);
            if ($pubKey === FALSE){return false;}

            $pubKey = $pubKey["key"];

            $data = 'plaintext data goes here';

            // Encrypt the data to $encrypted using the public key
            $res = openssl_public_encrypt($data, $encrypted, $pubKey);
            if ($res === FALSE){return false;}

            // Decrypt the data using the private key and cart the results in $decrypted
            $res = openssl_private_decrypt($encrypted, $decrypted, $privKey);
            if ($res === FALSE){return false;}

            return $decrypted;
        }
        
        echo "<li>OpenSSL: ";
        $res = testOpenSSL();
        if ($res === FALSE)
        {
            echo "<span style='color: red;'>Fail</span>";
        } else {
            echo "<span style='color: green;'>Pass: ".$res."</span>";
        }
        echo "</li>";
        
        ?>
        </ul>
        </span>
    </div>
</div>

<div class="clearfix"><p>&nbsp;</p></div>

<div class="container">
    <div class="row">
        <?php phpinfo(); ?>
    </div>
</div>