<!-- /*************** ADD NEW PRODUCT FORM ***************/ -->
<form id="frm_admin_new_product" name="frm_admin_new_product" class="form-horizontal" method="POST">
    <div id="newProductModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newProductModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times</button>
            <h3 id="newProductModalLabel">Add New Product</h3>
        </div>
        <div class="modal-body">

            <!-- Results -->
            <div id='results'></div>
            
            <!-- Cart Owner -->
            <div class="control-group">
                <label class="control-label" for="productCartID">Cart Owner</label>
                <div class="controls">
                    <select id="productCartID" name="productCartID">
                        <?php
                        $cart = new killerCart\KillerCart($_SESSION['cartID']);
                        foreach ($cart->getCartIDs('All') as $k => $v) {
                            // ACL Check
                            if ($_SESSION['user']['usergroup']['usergroupID'] != 1 && ($v['cartID'] != $_SESSION['cartID'])
                            ) {
                                continue;
                            }
                            $s = $cart->getCartInfo($v['cartID']);
                            ?>
                            <option value='<?php echo $s['cartID']; ?>'><?php echo $s['cartName']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
            </div>

            <!-- Parent Category -->
            <div class="control-group">
                <label class="control-label" for="productCategoryID"><strong>*Category</strong></label>
                <div class="controls">
                    <div id='productCategoryID_dynamic'>
                        <select disabled><option disabled>Select cart first</option></select>
                    </div>
                </div>
            </div>

            <!-- Parent Product -->
            <div class="control-group">
                <label class="control-label" for="productParentID">Parent Product</label>
                <div class="controls">
                    <div id='productParentID_dynamic'>
                        <select disabled><option disabled>Select cart first</option></select>
                    </div>
                </div>
            </div>

            <!-- Product Name -->
            <div class="control-group">
                <label class="control-label" for="productName"><strong>*Name</strong></label>
                <div class="controls">
                    <input type="text" id="productName" name="productName" placeholder="Enter Product Name">
                </div>
            </div>

            <!-- Product SKU -->
            <div class="control-group">
                <label class="control-label" for="productSKU">Product SKU</label>
                <div class="controls">
                    <input type="text" id="productSKU" name="productSKU" placeholder="Enter Product SKU">
                </div>
            </div>

            <!-- Product Price -->
            <div class="control-group">
                <label class="control-label" for="productPrice">Price</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on">$</span>
                        <input type="text" id="productPrice" name="productPrice" placeholder="Enter Product Price" value='0.00' class='span2'>
                    </div>
                </div>
            </div>        

            <!-- Description Public -->
            <input type='hidden' id='productDescriptionPublic' name='productDescriptionPublic' value='' />

            <!-- Description Private -->
            <input type='hidden' id='productDescriptionPrivate' name='productDescriptionPrivate' value='' />

            <!-- Email notification -->
            <input type='hidden' id='productEmail' name='productEmail' value='' />

            <!-- Taxable -->
            <div class="control-group">
                <label class="control-label" for="productTaxable">
                    Taxable
                </label>
                <div class="controls">
                    <select name='productTaxable' class='span2'>
                        <option value='2' selected>Inherit from Category</option>
                        <option value='1'>Taxable</option>
                        <option value='0'>Nontaxable</option>
                    </select>

                    <!-- Taxable Help -->
                    <span class="help-inline">
                        <button id='productTaxableHelpModalBtn' type='button' class="btn btn-mini"><small>Need Help?</small></button>
                    </span>
                    <div id="productTaxableHelpModal" class='hidden'>
                        <strong>Inherit from Category</strong><br />
                        Inherits taxable status from category<br />
                        <strong>Taxable</strong><br />
                        Override category taxable status and force product to be taxable<br />
                        <strong>Nontaxable</strong><br />
                        Override category taxable status and force product to be nontaxable
                    </div>
                </div>
            </div>

            <!-- Privacy -->
            <div class="control-group">
                <label class="control-label" for="productPrivacy">
                    Privacy
                </label>
                <div class="controls">
                    <select id='productPrivacy' name='productPrivacy' class='span2'>
                        <option value='2' selected>Inherit from Category</option>
                        <option value='0'>Public</option>
                        <option value='1'>Private</option>
                    </select>

                    <!-- Privacy Help -->
                    <span class="help-inline">
                        <button id='productPrivacyHelpModalBtn' type='button' class="btn btn-mini"><small>Need Help?</small></button>
                    </span>
                    <div id="productPrivacyHelpModal" class='hidden'>
                        <strong>Inherit from Category</strong><br />
                        Inherits privacy from category<br />
                        <strong>Public</strong><br />
                        Override category privacy and force product to be public<br />
                        <strong>Private</strong><br />
                        Override category privacy and force product to be private
                    </div>
                </div>
            </div>

        </div>
        
        <!-- Buttons -->
        <div class="modal-footer">
            <input type="hidden" name="p" value="<?php echo $_REQUEST['p']; ?>" />
            <input type='hidden' name='m' value='ajax' />
            <input type='hidden' name='a' value='edit_product' />
            <input type='hidden' name='s' value='2' />
            <button id='createProductCloseBtn' class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button id='createProductBtn' type="button" class="btn btn-success">
                <i class='icon-ok-sign icon-white'></i>&nbsp;Add New Product
            </button>
        </div>

    </div>
</form><!--#frm_admin_new_product-->

<?php
$thisDir = dirname(__FILE__);
$pageJavaScript[] = "<script type='text/javascript'>".
        str_replace('@cartPublicUrl@',
                cartPublicUrl,
                file_get_contents($thisDir.'/product_new_form.js')
                )."</script>";