<?php
// Subcategories
$subProds       = FALSE;
$lastCatID  = 0;
// Begin constructing output
$out           = "
    <div class='container'>
        <div class='row'>
            <div class='span12'>
                <table class='table table-condensed table-bordered table-striped'>
                    <tr>
                        <th>Product Name</th>
                        <th>SKU</th>
                        <th>Description (Private)</th>
                        <th>Description (Public)</th>
                    </tr>";
//
// Foreach product
//
foreach ($productIDs as $productID) {

    // Load info
    $p = $product->getProductInfo($productID['productID']);
    
    //
    // ACL Check: Cart limit
    //
    if (empty($_SESSION['user']['ACL']['global']['read'])) {
        if ($_SESSION['cartID'] != $p['cartID']) {
            continue;
        }
    }
    
    // Search array
    $allProdNames[] = $p['productName'];

    // @todo Child Product Grouping (similar to way sub-categories work)
    
    // New row for cat separation
    // If this cat is different from last cat
    if ($p['categoryID'] != $lastCatID) {
        // New group
        $catInfo = $category->getCategoryInfo($p['categoryID']);
        $lastCatID       = $p['categoryID'];
        $lastCatName     = $catInfo['categoryName'];
        $out .= "<tr><th colspan='4'><h2>" . $lastCatName . "&nbsp;<small>Products</small></h2></th></tr>";
        $subProds            = TRUE;
    }

    //
    // New Column / Data
    //
    $out .= "
            <tr>
                <td class='span3'>
                    <a name='productID' href='?p=product&a=edit_product&productID=" . $p['productID'] . "'>
                        <h5>".$p['productName']."</h5>
                    </a>
                </td>
                <td class='span1'>
                    ".$p['productSKU']."
                </td>
                <td class='span4'>";
    if (!empty($p['productDescriptionPrivate'])) {
        $out .= htmlspecialchars(substr(trim(killerCart\Util::convertBRToNL($p['productDescriptionPrivate'])), 0, 100)) . "...";
    }
    $out .= "
                </td>
                <td class='span4'>";
    if (!empty($p['productDescriptionPublic'])) {
        $out .= htmlspecialchars(substr(trim(killerCart\Util::convertBRToNL($p['productDescriptionPublic'])), 0, 100)) . "...";
    }
    $out .= "
                </td>
            </tr>";
}
$out .= "       </table>
            </div>
        </div>
    </div>";

// Display Output
echo $out;